main = ".open-next/worker.js"
name = "invoicely-web"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# r2 Buckets
[[r2_buckets]]
binding = "R2_IMAGES"
bucket_name = "invoicely"

# To enable logging in Cloudflare Logs
[observability.logs]
enabled = true
