main = ".open-next/worker.js"
name = "invoicely-migrate"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# To enable logging in Cloudflare Logs
[observability.logs]
enabled = true